services:
  notification_service:
    build: .
    ports:
      - "8000:8000"

  notification_worker:
    build: .
    command: ["celery", "-A", "notification_service.config", "worker"]
    depends_on:
      - rabbitmq

  notification_scheduler:
    build: .
    command: ["celery", "-A", "notification_service.config", "beat"]
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3